const projects = [{
    id: 1,
    title: 'Support desk',
    description: "Support desk web app is made to provide support to the users. It's a Mern Stack App. In this one can create, view, close ticket, add notes and do all crud operations. It’s authenticated by Json web token.",
    imgUrl: 'supportdesk',
    projectUrl: '/projects/1',
    githubUrl: 'https://dksupportdesk.herokuapp.com/',
    watchLiveUrl: 'https://github.com/Dikshant09/support-desk',
}, 
{
    id: 2,
    title: 'Github Finder',
    description: "This app is made up using React, Tailwind CSS. In this app one can check github profile of user with all info such as repos, followers, gists, etc... ",
    imgUrl: 'github',
    projectUrl: '/projects/2',
    githubUrl: 'https://github-finder-dikshant09.vercel.app/',
    watchLiveUrl: 'https://github.com/Dikshant09/github-finder',
  },
  {
    id: 3,
    title: 'House Marketplace',
    description: "It's real estate website to buy and sell house. Here one can add, edit, delete and post listing in real-time. It's madeup using React as frontend and Firebase as backend..",
    imgUrl: 'housemarketplace',
    projectUrl: '/projects/3',
    watchLiveUrl: 'https://github.com/Dikshant09/house-marketplace',
    githubUrl: 'https://house-marketplace-bay.vercel.app/',
  },
  {
    id: 4,
    title: 'Feedback UI',
    description: "It's a Full Stack App : Frontend is made up using React and Backend is made up using JSON Server. This is a React app to leave feedback for a product or service. Here one can add, update and delete feedback.",
    imgUrl: 'feedback',
    projectUrl: '/projects/4',
    watchLiveUrl: 'https://github.com/Dikshant09/feedback-app',
    githubUrl: 'https://dk-feedback-ui.herokuapp.com/',
},
    {
    id: 5,
    title: 'Monster Duplex',
    imgUrl: 'monster',
    description: "It's Simple Fun Project, in which I created monster's site which is made up using react...",
    projectUrl: '/projects/5',
    watchLiveUrl: 'https://github.com/Dikshant09/monsters-duplex',
    githubUrl: 'https://dikshant09.github.io/monsters-duplex/',
    },
  {
    id: 6,
    title: 'Heart Disease Classification',
    description: 'Heart Disease Prediction Model. It can predict the whether someone has heart disease or not, given health info. It is implemented using pandas, numpy, matplotlib and model from sckit-learn.',
    imgUrl: 'heartdisease',
    projectUrl: '/projects/6',
    watchLiveUrl: 'https://github.com/Dikshant09/ML-Projects/tree/master/Machine%20Learning/End%20to%20End%20Heart%20Disease%20Classification',
  },
  {
      id: 7,
      title: 'Bulldozer Price Prediction',
      imgUrl: 'bulldozer',
      description: "In this project a regression model is created to predict the sale price of bulldozers sold at auctions. It is implemented using pandas, numpy, matplotlib and model from sckit-learn.",
      projectUrl: '/projects/7',
      watchLiveUrl: 'https://github.com/Dikshant09/ML-Projects/blob/master/Machine%20Learning/End%20to%20End%20Bulldozer-price-prediction-project/end-to-end-bulldozer-price-regression.ipynb',
  },
  {
    id: 8,
    title: 'Dog Breed Identification',
    imgUrl: 'dog',
    description: "End-to-end Multi-class Dog Breed Classification model. This model is capable to recognize 120 breeds of dogs. It is implemented using Pandas, numpy, matplotlib, scikit-learn and model from TensorFlow.",
    projectUrl: '/projects/8',
    watchLiveUrl: 'https://github.com/Dikshant09/ML-Projects/blob/master/Machine%20Learning/End%20to%20End%20Dog%20Breed%20Identification/dog-vision.ipynb',
},
{
    id: 9,
    title: 'Disease Prediction',
    imgUrl: 'diseaseprediction',
    projectUrl: '/projects/9',
    description: "This notebook looks into using machine learning and data science libraries in an attempt to build a machine learning model capable of predicting someone's disease given symptoms",
    watchLiveUrl: 'https://github.com/cupunjab/BruteForce/blob/master/ML/Jupyter%20Notebook/Disease%20Prediction%20Model.ipynb',
  }
];

export default projects;